@startuml "MarsRover-Kata-UML.png"

interface IVehicle
{
+ void TurnLeft()
+ void TurnRight()
+ void Move()
}

interface ISurface
{
+ int Lenght_X
+ int Width_Y
}

interface IPosition
{
+ List<int> initialPosition
}

interface INavigation
{
+ void RunCommand(IVehicle marsRover)
}

class MarsRover implements IVehicle
class MarsPlateau implements ISurface
class MoveLeft implements INavigation
class MoveRight implements INavigation
class PositionInterpreter implements IPosition

class NavigateForward implements INavigation
class NavigationInterface
class ChangeDirection
class MoveForward


@enduml